AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31' # Indica que no se procesa como una tamplate normal, sino que usa SAM
Description: VotaNet Serverless backend - API Gateway y Lambda Python 3.1

# 1. Configuracion Global para funciones Serverless (principio DRY: Don't repeat yourself)
Globals: # sirve para todas las lambdas, similar a un x-common en docker
  Function:
    Timeout: 10 # por defecto 3 segundos. Tiempo maximo de vida de la lambda, si no logra responder el sistema falla, hay que escoger un numero adecuado
    MemorySize: 128 # (0.08 vCPU) la ram determina la CPU, 1024mb (1 gb) --> 1 vCPU
    Runtime: python3.12
    # VpcConfig # por si necesitaramos ir a una VPC
    # ReservedConcurrentExecutions: Límite de concurrencia. Evita que millones de peticiones saturen tu base de datos o agoten la cuota de tu cuenta.
    Environment:
      Variables:
        LOG_LEVEL: INFO
        DYNAMO_KEY: cc
        # Conexion con la tabla de DynamoDB importado el export de la fase 1
        DYNAMO_TABLE: !ImportValue DynamoLab

Resources:
  # 2. API Gateway REST con CORS habilitado
  VotaNetApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors: # esto le permite a la API responder antes OPTIONS sin despertar a la lambda. La lambda tambien las necesita para que el navegador no bloquee la respuesta entregada
        AllowMethods: "'GET, POST, OPTIONS'"
        AllowHeaders: "'Content-Type, Authorization'"
        AllowOrigin: "'*'"
      
  # 3. Role IAM de ejecusion para la lambda
  VotaNetLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: votanet-dev-lambda-execution-role
      AssumeRolePolicyDocument: # trust policy (sombrero
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com # autorizacion solo a lambdas
            Action: sts:AssumeRole
      ManagedPolicyArns:
        # Reutilizacion de politicas previamente establecidas
        - !ImportValue LambdaPolicyDynamoDBArn
        - !ImportValue LambdaPolicyCWArn
    
  # 4. Funcion Serverless Lambda
  VotaNetLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: votanet-dev-query-voter # nombre fisico en la consola web aws
      Handler: lambda_function.lambda_handler # llama al codigo .py, para la lambda en el micro servidor que la corre, es como from lambda_function import lambda_handler
      CodeUri: ./ # en esta misma ruta, para SAM
      Role: !GetAtt VotaNetLambdaRole.Arn
      Events:
      # Ruta 1: Get /voters/{id} (consulta por parametro de ruta)
        GetVoterByPath:
          Type: Api
          Properties:
            RestApiId: !Ref VotaNetApi
            Path: /voters/{id}
            Method: GET
        # Ruta 2: GET /voters (consula por query strings ?cc=...)
        GetVoterByQuery:
          Type: Api
          Properties:
            RestApiId: !Ref VotaNetApi
            Path: /voters
            Method: GET
        # Ruta 3: POST /voters (consulta con body)
        GetVoterByBody:
          Type: Api
          Properties:
            RestApiId: !Ref VotaNetApi
            Path: /voters
            Method: POST

# Salidas utiles para probar de inmediato en la terminal
Outputs:
  ApiEndpoint:
    Value: !Sub "https://${VotaNetApi}.execute-api.${AWS::Region}.amazonaws.com/dev/voters" # AWS tiene instalado un certificado SSL/TLS comodín (Wildcard Certificate) de alta seguridad a nivel mundial para *.execute-api.<region>.amazonaws.com.
    Description: Url base de API Gateway para consultar votantes
  
  LambdaFunctionArn:
    Value: !GetAtt VotaNetLambdaFunction.Arn
    Description: ARN de la function lambda en aws