version: 0.2 # version actual y recomendada para CodeBuild

# 1. Definicion de las fases de compilacion en CodeBuild
# instrucciones para el contenedor de CodeBuild
phases:
  # prepara el entorno, en este caso con python 3.12, sam cli ya esta por defecto
  install:
    runtime-versions:
      python: 3.12
    # todo comienza en la raiz infra_own
    commands:
      - echo "=== Fase 1: verificando herramientass en CodeBuild ==="
      - python --version
      - sam --version

  build:
    commands:
      - echo "=== Fase 2: Compilando aplicacion Serverless con SAM ==="
      - cd app
      - sam build

  post_build:
    commands:
      - echo "=== Fase 3: Empaquetando y subiendo zip a s3 ==="
      # Toma el template compulado, sube el zip a s3 y genera un packaged.yaml
      - cd app
      - sam package --s3-bucket ${S3_BUCKET} --output-template-file packaged.yaml
      # S3_BUCKET viene desde la fase 2, en este caso seria votanet-artefacts-841702867308-us-east-2
      - echo "=== Empaquetado terminado con exito. Archivo listo: packaged.yaml"

# 2. Artefactos que viajan hacia la siguiente etapa del Pipeline (CloudFormation)
artifacts:
  # esto es necesario al no tener el buildspec.yml donde esta la plantilla que va a montar
  base-directory: app
  files:
    - packaged.yaml
    - samconfig.toml
